// ______________________________________________________
// Generated by sql2java - https://github.com/10km/sql2java-2-6-7 (custom branch) 
// modified by guyadong from
// sql2java original version https://sourceforge.net/projects/sql2java/ 
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
// ______________________________________________________

package net.gdface.facelog.dborm.image;

import net.gdface.facelog.dborm.exception.DAOException;
import net.gdface.facelog.dborm.TableListener;
/**
 * Listener that is notified of fl_image table changes.
 * @author sql2java
 */
public interface FlImageListener extends TableListener
{
    /**
     * This adapter class provides default implementations for the
     * methods described by the {@link FlImageListener} interface.<br>
     * 
     * @see FlImageListener
     * @author sql2java
     *
     */
    public static class Adapter implements FlImageListener{

        @Override
        public void beforeInsert(FlImageBean bean) throws DAOException {}

        @Override
        public void afterInsert(FlImageBean bean) throws DAOException {
        }

        @Override
        public void beforeUpdate(FlImageBean bean) throws DAOException {}

        @Override
        public void afterUpdate(FlImageBean bean) throws DAOException {}

        @Override
        public void beforeDelete(FlImageBean bean) throws DAOException {}

        @Override
        public void afterDelete(FlImageBean bean) throws DAOException {}
    }
    /**
     * Invoked just before inserting a FlImageBean record into the database.
     *
     * @param bean the FlImageBean that is about to be inserted
     */
    public void beforeInsert(FlImageBean bean) throws DAOException;


    /**
     * Invoked just after a FlImageBean record is inserted in the database.
     *
     * @param bean the FlImageBean that was just inserted
     */
    public void afterInsert(FlImageBean bean) throws DAOException;


    /**
     * Invoked just before updating a FlImageBean record in the database.
     *
     * @param bean the FlImageBean that is about to be updated
     */
    public void beforeUpdate(FlImageBean bean) throws DAOException;


    /**
     * Invoked just after updating a FlImageBean record in the database.
     *
     * @param bean the FlImageBean that was just updated
     */
    public void afterUpdate(FlImageBean bean) throws DAOException;


    /**
     * Invoked just before deleting a FlImageBean record in the database.
     *
     * @param bean the FlImageBean that is about to be deleted
     */
    public void beforeDelete(FlImageBean bean) throws DAOException;


    /**
     * Invoked just after deleting a FlImageBean record in the database.
     *
     * @param bean the FlImageBean that was just deleted
     */
    public void afterDelete(FlImageBean bean) throws DAOException;

}
