// ______________________________________________________
// Generated by sql2java - https://github.com/10km/sql2java-2-6-7 (custom branch) 
// modified by guyadong from
// sql2java original version https://sourceforge.net/projects/sql2java/ 
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
// ______________________________________________________

package net.gdface.facelog.dborm.image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.concurrent.Callable;
import java.util.concurrent.atomic.AtomicInteger;

import net.gdface.facelog.dborm.Constant;
import net.gdface.facelog.dborm.Manager;
import net.gdface.facelog.dborm.TableListener;
import net.gdface.facelog.dborm.TableManager;
import net.gdface.facelog.dborm.exception.DAOException;
import net.gdface.facelog.dborm.exception.DataAccessException;
import net.gdface.facelog.dborm.exception.ObjectRetrievalException;
import net.gdface.facelog.dborm.image.FlImageBean;
import net.gdface.facelog.dborm.image.FlImageManager;

/**
 * Handles database calls (save, load, count, etc...) for the fl_store table.
 * @author sql2java
 */
public class FlStoreManager extends TableManager.Adapter<FlStoreBean>
{
    /**
     * Tablename.
     */
    public static final String TABLE_NAME="fl_store";

   /**
     * Contains all the primarykey fields of the fl_store table.
     */
    public static final String[] PRIMARYKEY_NAMES =
    {
        "md5"
    };

    /**
    * @return tableName
    */
    public String getTableName() {
        return TABLE_NAME;
    }

    public String getFields() {
        return FL_STORE_FIELDS;
    }
    
    public String getFullFields() {
        return FL_STORE_FULL_FIELDS;
    }
    
    /**
    * @return primarykeyNames
    */
    public String[] getPrimarykeyNames() {
        return PRIMARYKEY_NAMES;
    }

    private static FlStoreManager singleton = new FlStoreManager();

    /**
     * Get the FlStoreManager singleton.
     *
     * @return FlStoreManager
     */
    public static FlStoreManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new FlStoreBean instance.
     *
     * @return the new FlStoreBean
     */
    public FlStoreBean createBean()
    {
        return new FlStoreBean();
    }
    
    @Override
    protected Class<FlStoreBean> _beanType(){
        return FlStoreBean.class;
    }
    
    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a {@link FlStoreBean} from the fl_store using primary key fields.
     *
     * @param md5 String - PK# 1
     * @return a unique FlStoreBean or {@code null} if not found or have null argument
     * @throws DAOException
     */
    //1
    @SuppressWarnings("unused")
    public FlStoreBean loadByPrimaryKey(String md5) throws DAOException
    {
        if(null == md5){
            return null;
        }
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuilder sql = new StringBuilder("SELECT " + FL_STORE_FIELDS + " FROM fl_store WHERE md5=?");
            // System.out.println("loadByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (md5 == null) { ps.setNull(1, Types.CHAR); } else { ps.setString(1, md5); }
            List<FlStoreBean> pReturn = this.loadByPreparedStatementAsList(ps);
            if (0 == pReturn.size()) {
                return null;
            } else {
                return pReturn.get(0);
            }
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //1.2
    @Override
    public FlStoreBean loadByPrimaryKey(FlStoreBean bean) throws DAOException
    {
        return bean==null?null:loadByPrimaryKey( bean.getMd5());
    }
    
    /**
     * Loads a {@link FlStoreBean} from the fl_store using primary key fields.
     * @param keys primary keys value:<br> 
     * @return a unique {@link FlStoreBean} or {@code null} if not found
     * @see {@link #loadByPrimaryKey(String md5)}
     */
    //1.3
    @Override
    public FlStoreBean loadByPrimaryKey(Object ...keys) throws DAOException{
        if(keys.length != 1 )
            throw new IllegalArgumentException("argument number mismatch with primary key number");
        if(! (keys[0] instanceof String))
            throw new IllegalArgumentException("invalid type for the No.1 argument,expected type:String");
        return loadByPrimaryKey((String)keys[0]);
    }
    
    /**
     * Returns true if this fl_store contains row with primary key fields.
     * @param md5 String - PK# 1
     * @throws DAOException
     * @see #loadByPrimaryKey(String md5)
     */
    //1.3
    public boolean existsPrimaryKey(String md5) throws DAOException
    {
        return null!=loadByPrimaryKey(md5 );
    }
    
    /**
     * Delete row according to its primary keys.<br>
     * all keys must not be null
     * 
     * @param md5 String - PK# 1
     * @return the number of deleted rows
     * @throws DAOException
     * @see {@link #delete(FlStoreBean)}
     */
    //2
    public int deleteByPrimaryKey(String md5) throws DAOException
    {
        FlStoreBean bean=createBean();
        bean.setMd5(md5);
        return this.delete(bean);
    }

    /**
     * Delete row according to primary keys of bean.<br>
     * 
     * @param bean will be deleted ,all keys must not be null
     * @return the number of deleted rows,0 returned if bean is null
     * @throws DAOException
     */
    //2
    @Override
    public int delete(FlStoreBean bean) throws DAOException
    {
        if(null == bean) return 0;
        if(null == bean.getMd5()){
            throw new IllegalArgumentException("primary keys must no be null ");
        }
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            this.listenerContainer.beforeDelete(bean); // listener callback
            c = this.getConnection();
            StringBuilder sql = new StringBuilder("DELETE FROM fl_store WHERE md5=?");
            // System.out.println("deleteByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (bean.getMd5() == null) { ps.setNull(1, Types.CHAR); } else { ps.setString(1, bean.getMd5()); }
            int _rows=ps.executeUpdate();
            if(_rows>0)
                this.listenerContainer.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Delete row according to its primary keys.
     *
     * @param keys primary keys value:<br> 
     * @return the number of deleted rows
     * @see {@link #delete(FlStoreBean)}
     */   
    //2.1
    @Override
    public int deleteByPrimaryKey(Object ...keys) throws DAOException{
        if(keys.length != 1 )
            throw new IllegalArgumentException("argument number mismatch with primary key number");
        FlStoreBean bean=createBean();   
        if(null!= keys[0] && !(keys[0] instanceof String))
            throw new IllegalArgumentException("invalid type for the No.1 argument,expected type:String");
        bean.setMd5((String)keys[0]);
        return delete(bean);
    }
    
 
    //////////////////////////////////////
    // IMPORT KEY GENERIC METHOD
    //////////////////////////////////////
    
    private static final Class<?>[] importedBeanTypes = new Class<?>[]{FlImageBean.class,FlImageBean.class};

    /**
     * @see #getImportedBeansAsList(FlStoreBean,int)
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends net.gdface.facelog.dborm.BaseBean<?>> T[] getImportedBeans(FlStoreBean bean, int ikIndex) throws DAOException {
        return getImportedBeansAsList(bean, ikIndex).toArray((T[])java.lang.reflect.Array.newInstance(importedBeanTypes[ikIndex],0));
    }
    
    /**
     * Retrieves imported T objects by ikIndex.<br>
     * @param <T>
     * <ul>
     *     <li> {@link Constant#FL_STORE_IK_FL_IMAGE_MD5} -> {@link FlImageBean}</li>
     *     <li> {@link Constant#FL_STORE_IK_FL_IMAGE_THUMB_MD5} -> {@link FlImageBean}</li>
     * </ul>
     * @param bean the {@link FlStoreBean} object to use
     * @param ikIndex valid values: {@link Constant#FL_STORE_IK_FL_IMAGE_MD5},{@link Constant#FL_STORE_IK_FL_IMAGE_THUMB_MD5}
     * @return the associated T beans or {@code null} if {@code bean} is {@code null}
     * @throws DAOException
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends net.gdface.facelog.dborm.BaseBean<?>> List<T> getImportedBeansAsList(FlStoreBean bean,int ikIndex)throws DAOException{
        switch(ikIndex){
        case FL_STORE_IK_FL_IMAGE_MD5:
            return (List<T>)this.getImageBeansByMd5AsList(bean);
        case FL_STORE_IK_FL_IMAGE_THUMB_MD5:
            return (List<T>)this.getImageBeansByThumbMd5AsList(bean);
        }
        throw new IllegalArgumentException(String.format("invalid ikIndex %d", ikIndex));
    }
    
    /**
     * Set the T objects as imported beans of bean object by ikIndex.<br>
     * @param <T> see also {@link #getImportedBeansAsList(FlStoreBean,int)}
     * @param bean the {@link FlStoreBean} object to use
     * @param importedBeans the FlImageBean array to associate to the {@link FlStoreBean}
     * @param ikIndex valid values: see also {@link #getImportedBeansAsList(FlStoreBean,int)}
     * @return importedBeans always
     * @throws DAOException
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends net.gdface.facelog.dborm.BaseBean<?>> T[] setImportedBeans(FlStoreBean bean,T[] importedBeans,int ikIndex)throws DAOException{
        switch(ikIndex){
        case FL_STORE_IK_FL_IMAGE_MD5:
            return (T[])setImageBeansByMd5(bean,(FlImageBean[])importedBeans);
        case FL_STORE_IK_FL_IMAGE_THUMB_MD5:
            return (T[])setImageBeansByThumbMd5(bean,(FlImageBean[])importedBeans);
        }
        throw new IllegalArgumentException(String.format("invalid ikIndex %d", ikIndex));
    }
    /**
     * Set the importedBeans associates to the bean by ikIndex<br>
     * @param <T> see also {@link #getImportedBeansAsList(FlStoreBean,int)}
     * @param bean the {@link FlStoreBean} object to use
     * @param importedBeans the <T> object to associate to the {@link FlStoreBean}
     * @param ikIndex valid values: see also {@link #getImportedBeansAsList(FlStoreBean,int)}

     * @return importedBeans always
     * @throws DAOException
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends net.gdface.facelog.dborm.BaseBean<?>,C extends java.util.Collection<T>> C setImportedBeans(FlStoreBean bean,C importedBeans,int ikIndex)throws DAOException{
        switch(ikIndex){
        case FL_STORE_IK_FL_IMAGE_MD5:
            return (C)setImageBeansByMd5(bean,(java.util.Collection<FlImageBean>)importedBeans);
        case FL_STORE_IK_FL_IMAGE_THUMB_MD5:
            return (C)setImageBeansByThumbMd5(bean,(java.util.Collection<FlImageBean>)importedBeans);
        }
        throw new IllegalArgumentException(String.format("invalid ikIndex %d", ikIndex));
    }
 
    //////////////////////////////////////
    // GET/SET IMPORTED KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the {@link FlImageBean} object from the fl_image.md5 field.<BR>
     * FK_NAME : fl_image_ibfk_1 
     * @param bean the {@link FlStoreBean}
     * @return the associated {@link FlImageBean} beans or {@code null} if {@code bean} is {@code null}
     * @throws DAOException
     */
    //3.1 GET IMPORTED
    public FlImageBean[] getImageBeansByMd5(FlStoreBean bean) throws DAOException
    {
        return getImageBeansByMd5AsList(bean).toArray(new FlImageBean[0]);
    }
    /**
     * Retrieves the {@link FlImageBean} object from the fl_image.md5 field.<BR>
     * FK_NAME : fl_image_ibfk_1 
     * @param md5 String - PK# 1
     * @return the associated {@link FlImageBean} beans or {@code null} if {@code bean} is {@code null}
     * @throws DAOException
     */
    //3.1.2 GET IMPORTED
    public FlImageBean[] getImageBeansByMd5(String storeMd5) throws DAOException
    {
        FlStoreBean bean = createBean();
        bean.setMd5(storeMd5);
        return getImageBeansByMd5(bean);
    }
    /**
     * Retrieves the {@link FlImageBean} object from fl_image.md5 field.<BR>
     * FK_NAME:fl_image_ibfk_1
     * @param bean the {@link FlStoreBean}
     * @return the associated {@link FlImageBean} beans 
     * @throws DAOException
     */
    //3.2 GET IMPORTED
    public List<FlImageBean> getImageBeansByMd5AsList(FlStoreBean bean) throws DAOException
    {
        if(null == bean)return new java.util.ArrayList<FlImageBean>();
        FlImageBean other = FlImageManager.getInstance().createBean();
        other.setMd5(bean.getMd5());
        return FlImageManager.getInstance().loadUsingTemplateAsList(other);
    }
    /**
     * Retrieves the {@link FlImageBean} object from fl_image.md5 field.<BR>
     * FK_NAME:fl_image_ibfk_1
     * @param md5 String - PK# 1
     * @return the associated {@link FlImageBean} beans 
     * @throws DAOException
     */
    //3.2.2 GET IMPORTED
    public List<FlImageBean> getImageBeansByMd5AsList(String storeMd5) throws DAOException
    {
         FlStoreBean bean = createBean();
        bean.setMd5(storeMd5);
        return getImageBeansByMd5AsList(bean);
    }
    /**
     * set  the {@link FlImageBean} object array associate to FlStoreBean by the fl_image.md5 field.<BR>
     * FK_NAME : fl_image_ibfk_1 
     * @param bean the referenced {@link FlStoreBean}
     * @param importedBeans imported beans from fl_image
     * @return importedBeans always
     * @throws DAOException
     * @see {@link FlImageManager#setReferencedByMd5(FlImageBean, FlStoreBean)
     */
    //3.3 SET IMPORTED
    public FlImageBean[] setImageBeansByMd5(FlStoreBean bean , FlImageBean[] importedBeans) throws DAOException
    {
        if(null != importedBeans){
            for( FlImageBean importBean : importedBeans ){
                FlImageManager.getInstance().setReferencedByMd5(importBean , bean);
            }
        }
        return importedBeans;
    }

    /**
     * set  the {@link FlImageBean} object collection associate to FlStoreBean by the fl_image.md5 field.<BR>
     * FK_NAME:fl_image_ibfk_1
     * @param bean the referenced {@link FlStoreBean} 
     * @param importedBeans imported beans from fl_image 
     * @return importedBeans always
     * @throws DAOException
     * @see {@link FlImageManager#setReferencedByMd5(FlImageBean, FlStoreBean)
     */
    //3.4 SET IMPORTED
    public <C extends java.util.Collection<FlImageBean>> C setImageBeansByMd5(FlStoreBean bean , C importedBeans) throws DAOException
    {
        if(null != importedBeans){
            for( FlImageBean importBean : importedBeans ){
                FlImageManager.getInstance().setReferencedByMd5(importBean , bean);
            }
        }
        return importedBeans;
    }

    /**
     * Retrieves the {@link FlImageBean} object from the fl_image.thumb_md5 field.<BR>
     * FK_NAME : fl_image_ibfk_2 
     * @param bean the {@link FlStoreBean}
     * @return the associated {@link FlImageBean} beans or {@code null} if {@code bean} is {@code null}
     * @throws DAOException
     */
    //3.1 GET IMPORTED
    public FlImageBean[] getImageBeansByThumbMd5(FlStoreBean bean) throws DAOException
    {
        return getImageBeansByThumbMd5AsList(bean).toArray(new FlImageBean[0]);
    }
    /**
     * Retrieves the {@link FlImageBean} object from the fl_image.thumb_md5 field.<BR>
     * FK_NAME : fl_image_ibfk_2 
     * @param md5 String - PK# 1
     * @return the associated {@link FlImageBean} beans or {@code null} if {@code bean} is {@code null}
     * @throws DAOException
     */
    //3.1.2 GET IMPORTED
    public FlImageBean[] getImageBeansByThumbMd5(String storeMd5) throws DAOException
    {
        FlStoreBean bean = createBean();
        bean.setMd5(storeMd5);
        return getImageBeansByThumbMd5(bean);
    }
    /**
     * Retrieves the {@link FlImageBean} object from fl_image.thumb_md5 field.<BR>
     * FK_NAME:fl_image_ibfk_2
     * @param bean the {@link FlStoreBean}
     * @return the associated {@link FlImageBean} beans 
     * @throws DAOException
     */
    //3.2 GET IMPORTED
    public List<FlImageBean> getImageBeansByThumbMd5AsList(FlStoreBean bean) throws DAOException
    {
        if(null == bean)return new java.util.ArrayList<FlImageBean>();
        FlImageBean other = FlImageManager.getInstance().createBean();
        other.setThumbMd5(bean.getMd5());
        return FlImageManager.getInstance().loadUsingTemplateAsList(other);
    }
    /**
     * Retrieves the {@link FlImageBean} object from fl_image.thumb_md5 field.<BR>
     * FK_NAME:fl_image_ibfk_2
     * @param md5 String - PK# 1
     * @return the associated {@link FlImageBean} beans 
     * @throws DAOException
     */
    //3.2.2 GET IMPORTED
    public List<FlImageBean> getImageBeansByThumbMd5AsList(String storeMd5) throws DAOException
    {
         FlStoreBean bean = createBean();
        bean.setMd5(storeMd5);
        return getImageBeansByThumbMd5AsList(bean);
    }
    /**
     * set  the {@link FlImageBean} object array associate to FlStoreBean by the fl_image.thumb_md5 field.<BR>
     * FK_NAME : fl_image_ibfk_2 
     * @param bean the referenced {@link FlStoreBean}
     * @param importedBeans imported beans from fl_image
     * @return importedBeans always
     * @throws DAOException
     * @see {@link FlImageManager#setReferencedByThumbMd5(FlImageBean, FlStoreBean)
     */
    //3.3 SET IMPORTED
    public FlImageBean[] setImageBeansByThumbMd5(FlStoreBean bean , FlImageBean[] importedBeans) throws DAOException
    {
        if(null != importedBeans){
            for( FlImageBean importBean : importedBeans ){
                FlImageManager.getInstance().setReferencedByThumbMd5(importBean , bean);
            }
        }
        return importedBeans;
    }

    /**
     * set  the {@link FlImageBean} object collection associate to FlStoreBean by the fl_image.thumb_md5 field.<BR>
     * FK_NAME:fl_image_ibfk_2
     * @param bean the referenced {@link FlStoreBean} 
     * @param importedBeans imported beans from fl_image 
     * @return importedBeans always
     * @throws DAOException
     * @see {@link FlImageManager#setReferencedByThumbMd5(FlImageBean, FlStoreBean)
     */
    //3.4 SET IMPORTED
    public <C extends java.util.Collection<FlImageBean>> C setImageBeansByThumbMd5(FlStoreBean bean , C importedBeans) throws DAOException
    {
        if(null != importedBeans){
            for( FlImageBean importBean : importedBeans ){
                FlImageManager.getInstance().setReferencedByThumbMd5(importBean , bean);
            }
        }
        return importedBeans;
    }

    /**
     * Save the FlStoreBean bean and referenced beans and imported beans into the database.
     *
     * @param bean the {@link FlStoreBean} bean to be saved
         * @param impImageByMd5 the {@link FlImageBean} beans refer to {@link FlStoreBean} 
     * @param impImageByThumbMd5 the {@link FlImageBean} beans refer to {@link FlStoreBean} 
     * @return the inserted or updated {@link FlStoreBean} bean
     * @throws DAOException
     */
    //3.5 SYNC SAVE 
    public FlStoreBean save(FlStoreBean bean
        
        , FlImageBean[] impImageByMd5 , FlImageBean[] impImageByThumbMd5 ) throws DAOException
    {
        if(null == bean) return null;
        bean = this.save( bean );
        this.setImageBeansByMd5(bean,impImageByMd5);
        FlImageManager.getInstance().save( impImageByMd5 );
        this.setImageBeansByThumbMd5(bean,impImageByThumbMd5);
        FlImageManager.getInstance().save( impImageByThumbMd5 );
        return bean;
    } 

    /**
     * Transaction version for sync save
     * @see {@link #save(FlStoreBean , FlImageBean[] , FlImageBean[] )}
     */
    //3.6 SYNC SAVE AS TRANSACTION
    public FlStoreBean saveAsTransaction(final FlStoreBean bean
        
        ,final FlImageBean[] impImageByMd5 ,final FlImageBean[] impImageByThumbMd5 ) throws DAOException
    {
        return this.runAsTransaction(new Callable<FlStoreBean>(){
            @Override
            public FlStoreBean call() throws Exception {
                return save(bean , impImageByMd5 , impImageByThumbMd5 );
            }});
    }
    /**
     * Save the FlStoreBean bean and referenced beans and imported beans into the database.
     *
     * @param bean the {@link FlStoreBean} bean to be saved
         * @param impImageByMd5 the {@link FlImageBean} bean refer to {@link FlStoreBean} 
     * @param impImageByThumbMd5 the {@link FlImageBean} bean refer to {@link FlStoreBean} 
     * @return the inserted or updated {@link FlStoreBean} bean
     * @throws DAOException
     */
    //3.7 SYNC SAVE 
    public FlStoreBean save(FlStoreBean bean
        
        , java.util.Collection<FlImageBean> impImageByMd5 , java.util.Collection<FlImageBean> impImageByThumbMd5 ) throws DAOException
    {
        if(null == bean) return null;
        bean = this.save( bean );
        this.setImageBeansByMd5(bean,impImageByMd5);
        FlImageManager.getInstance().save( impImageByMd5 );
        this.setImageBeansByThumbMd5(bean,impImageByThumbMd5);
        FlImageManager.getInstance().save( impImageByThumbMd5 );
        return bean;
    }

    /**
     * Transaction version for sync save
     * @see {@link #save(FlStoreBean , java.util.Collection , java.util.Collection )}
     */
    //3.8 SYNC SAVE AS TRANSACTION
    public FlStoreBean saveAsTransaction(final FlStoreBean bean
        
        ,final  java.util.Collection<FlImageBean> impImageByMd5 ,final  java.util.Collection<FlImageBean> impImageByThumbMd5 ) throws DAOException
    {
        return this.runAsTransaction(new Callable<FlStoreBean>(){
            @Override
            public FlStoreBean call() throws Exception {
                return save(bean , impImageByMd5 , impImageByThumbMd5 );
            }});
    }
    /**
     * Save the FlStoreBean bean and referenced beans and imported beans (array) into the database.
     *
     * @param bean the {@link FlStoreBean} bean to be saved
     * @param args referenced beans or imported beans<br>
     *      see also {@link #save(FlStoreBean , FlImageBean[] , FlImageBean[] )}
     * @return the inserted or updated {@link FlStoreBean} bean
     * @throws DAOException
     */
    //3.9 SYNC SAVE 
    @Override
    public FlStoreBean save(FlStoreBean bean,Object ...args) throws DAOException
    {
        if(args.length > 2)
            throw new IllegalArgumentException("too many dynamic arguments,max dynamic arguments number: 2");
        if( args.length > 0 && null != args[0] && !(args[0] instanceof FlImageBean[])){
            throw new IllegalArgumentException("invalid type for the No.1 dynamic argument,expected type:FlImageBean[]");
        }
        if( args.length > 1 && null != args[1] && !(args[1] instanceof FlImageBean[])){
            throw new IllegalArgumentException("invalid type for the No.2 dynamic argument,expected type:FlImageBean[]");
        }
        return save(bean,(args.length < 1 || null == args[0])?null:(FlImageBean[])args[0],(args.length < 2 || null == args[1])?null:(FlImageBean[])args[1]);
    } 

    /**
     * Save the FlStoreBean bean and referenced beans and imported beans (collection) into the database.
     *
     * @param bean the {@link FlStoreBean} bean to be saved
     * @param args referenced beans or imported beans<br>
     *      see also {@link #save(FlStoreBean , java.util.Collection , java.util.Collection )}
     * @return the inserted or updated {@link FlStoreBean} bean
     * @throws DAOException
     */
    //3.10 SYNC SAVE 
    @SuppressWarnings("unchecked")
    @Override
    public FlStoreBean saveCollection(FlStoreBean bean,Object ...args) throws DAOException
    {
        if(args.length > 2)
            throw new IllegalArgumentException("too many dynamic arguments,max dynamic arguments number: 2");
        if( args.length > 0 && null != args[0] && !(args[0] instanceof java.util.Collection)){
            throw new IllegalArgumentException("invalid type for the No.1 argument,expected type:java.util.Collection<FlImageBean>");
        }
        if( args.length > 1 && null != args[1] && !(args[1] instanceof java.util.Collection)){
            throw new IllegalArgumentException("invalid type for the No.2 argument,expected type:java.util.Collection<FlImageBean>");
        }
        return save(bean,(args.length < 1 || null == args[0])?null:(java.util.Collection<FlImageBean>)args[0],(args.length < 2 || null == args[1])?null:(java.util.Collection<FlImageBean>)args[1]);
    } 
     

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Deletes rows from the fl_store table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clauses.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    @Override
    public int deleteByWhere(String where) throws DAOException
    {
        if( !this.listenerContainer.isEmpty()){
            final DeleteBeanAction action = new DeleteBeanAction(); 
            this.loadByWhere(where,action);
            return action.getCount();
        }
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuilder sql = new StringBuilder("DELETE FROM fl_store " + where);
            // System.out.println("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________

    //13
    @Override
    public FlStoreBean insert(FlStoreBean bean) throws DAOException
    {
        // mini checks
        if (null == bean || !bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = null;

        try
        {
            c = this.getConnection();
            this.listenerContainer.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuilder("INSERT into fl_store (");

            if (bean.checkMd5Modified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("md5");
                _dirtyCount++;
            }

            if (bean.checkEncodingModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("encoding");
                _dirtyCount++;
            }

            if (bean.checkDataModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("data");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            // System.out.println("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            bean.isNew(false);
            bean.resetIsModified();
            this.listenerContainer.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //14
    @Override
    public FlStoreBean update(FlStoreBean bean) throws DAOException
    {
        // mini checks
        if (null == bean || !bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = null;

        try
        {
            c = this.getConnection();

            this.listenerContainer.beforeUpdate(bean); // listener callback
            sql = new StringBuilder("UPDATE fl_store SET ");
            boolean useComma=false;

            if (bean.checkMd5Modified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("md5=?");
            }

            if (bean.checkEncodingModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("encoding=?");
            }

            if (bean.checkDataModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("data=?");
            }
            sql.append(" WHERE ");
            sql.append("md5=?");
            // System.out.println("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                // System.out.println("The bean to look is not initialized... do not update.");
                return bean;
            }

            if (bean.getMd5() == null) { ps.setNull(++_dirtyCount, Types.CHAR); } else { ps.setString(++_dirtyCount, bean.getMd5()); }
            ps.executeUpdate();
            bean.resetIsModified();
            this.listenerContainer.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________
    //18
    @Override
    public FlStoreBean loadUniqueUsingTemplate(FlStoreBean bean) throws DAOException
    {
         FlStoreBean[] beans = this.loadUsingTemplate(bean);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }

    //20-5
    @Override
    public int loadUsingTemplate(FlStoreBean bean, int[] fieldList, int startRow, int numRows,int searchType, Action<FlStoreBean> action) throws DAOException
    {
        // System.out.println("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        StringBuilder sqlWhere = new StringBuilder("");
        String sql=createSelectSql(fieldList,this.fillWhere(sqlWhere, bean, searchType) > 0?" WHERE "+sqlWhere.toString():null);
        PreparedStatement ps = null;
        Connection connection = null;
        // logger.debug("sql string:\n" + sql + "\n");
        try {
            connection = this.getConnection();
            ps = connection.prepareStatement(sql,
                    ResultSet.TYPE_FORWARD_ONLY,
                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);
            return this.loadByPreparedStatement(ps, fieldList, startRow, numRows, action);
        } catch (DAOException e) {
            throw e;
        }catch (SQLException e) {
            throw new DataAccessException(e);
        } finally {
            this.getManager().close(ps);
            this.freeConnection(connection);
        }
    }

    //21
    @Override
    public int deleteUsingTemplate(FlStoreBean bean) throws DAOException
    {
        if(bean.checkMd5Initialized() && null != bean.getMd5()){
            return this.deleteByPrimaryKey(bean.getMd5());
        }
        if( !this.listenerContainer.isEmpty()){
            final DeleteBeanAction action=new DeleteBeanAction(); 
            this.loadUsingTemplate(bean,action);
            return action.getCount();
        }
        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = new StringBuilder("DELETE FROM fl_store ");
        StringBuilder sqlWhere = new StringBuilder("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0)
            {
                sql.append(" WHERE ").append(sqlWhere);
            }
            else
            {
                // System.out.println("The bean to look is not initialized... deleting all");
            }
            // System.out.println("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }



    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    //25
    @Override
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM fl_store " + where;
        // System.out.println("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table fl_store with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific FlStoreBean bean given the search type
     *
     * @param bean the FlStoreBean template to look for
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(FlStoreBean bean, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) AS MCOUNT FROM fl_store");
        StringBuilder sqlWhere = new StringBuilder("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0)
            {
                sql.append(" WHERE ").append(sqlWhere);
            }
            else
            {
                // System.out.println("The bean to look is not initialized... counting all...");
            }
            // System.out.println("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given StringBuilder with the sql where clauses constructed using the bean and the search type
     * @param sqlWhere the StringBuilder that will be filled
     * @param bean the bean to use for creating the where clauses
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clauses returned
     */
    protected int fillWhere(StringBuilder sqlWhere, FlStoreBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.checkMd5Modified()) {
                _dirtyCount ++;
                if (bean.getMd5() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("md5 IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("md5 ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.checkEncodingModified()) {
                _dirtyCount ++;
                if (bean.getEncoding() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("encoding IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("encoding ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.checkDataModified()) {
                _dirtyCount ++;
                if (bean.getData() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("data IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("data = ?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the PreparedStatement that will be filled
     * @param bean the bean to use for creating the where clauses
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clauses returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, FlStoreBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.checkMd5Modified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getMd5() + "]");
                        if (bean.getMd5() == null) { ps.setNull(++_dirtyCount, Types.CHAR); } else { ps.setString(++_dirtyCount, bean.getMd5()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getMd5() + "%]");
                        if ( bean.getMd5()  == null) { ps.setNull(++_dirtyCount, Types.CHAR); } else { ps.setString(++_dirtyCount, "%" + bean.getMd5() + "%"); }
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getMd5() + "]");
                        if ( bean.getMd5() == null) { ps.setNull(++_dirtyCount, Types.CHAR); } else { ps.setString(++_dirtyCount, "%" + bean.getMd5()); }
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getMd5() + "%]");
                        if (bean.getMd5()  == null) { ps.setNull(++_dirtyCount, Types.CHAR); } else { ps.setString(++_dirtyCount, bean.getMd5() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.checkEncodingModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getEncoding() + "]");
                        if (bean.getEncoding() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getEncoding()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getEncoding() + "%]");
                        if ( bean.getEncoding()  == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, "%" + bean.getEncoding() + "%"); }
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getEncoding() + "]");
                        if ( bean.getEncoding() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, "%" + bean.getEncoding()); }
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getEncoding() + "%]");
                        if (bean.getEncoding()  == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getEncoding() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.checkDataModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getData() + "]");
                if (bean.getData() == null) { ps.setNull(++_dirtyCount, Types.LONGVARBINARY); } else { ps.setBytes(++_dirtyCount, bean.getData()); }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of FlStoreBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting FlStoreBean table
     * @throws DAOException
     */
    //28
    public FlStoreBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        return this.decodeResultSetAsList(rs, fieldList, startRow, numRows).toArray(new FlStoreBean[0]);
    }

    /**
     * decode a resultset in a list of FlStoreBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting FlStoreBean table
     * @throws DAOException
     */
    //28-1
    public List<FlStoreBean> decodeResultSetAsList(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ListAction action = new ListAction();
        actionOnResultSet(rs, fieldList, numRows, numRows, action);
        return action.getList();
    }
    /** decode a resultset and call action
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param action interface obj for do something
     * @return the count dealt by action  
     * @throws DAOException
     * @throws IllegalArgumentException
     */
    //28-2
    public int actionOnResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows, Action<FlStoreBean> action) throws DAOException{
        try{
            int count = 0;
            if(0!=numRows){
                if( startRow<1 )
                    throw new IllegalArgumentException("invalid argument:startRow (must >=1)");
                if( null==action || null==rs )
                    throw new IllegalArgumentException("invalid argument:action OR rs (must not be null)");                    
                for(;startRow>1&&rs.next();--startRow);//skip to last of startRow
                if (fieldList == null) {
                    if(numRows<0)
                        for(;rs.next();++count)
                            action.call(decodeRow(rs, action.getBean()));
                    else
                        for(;rs.next() && count<numRows;++count)
                            action.call(decodeRow(rs, action.getBean()));
                }else {
                    if(numRows<0)
                        for(;rs.next();++count)
                            action.call(decodeRow(rs, fieldList,action.getBean()));
                    else
                        for(;rs.next() && count<numRows;++count)
                            action.call(decodeRow(rs, fieldList,action.getBean()));
                }
            }
            return count;
        }catch(DAOException e){
            throw e;
        }catch(SQLException e){
            throw new DataAccessException(e);
        }
    }

    /**
     * Transforms a ResultSet iterating on the fl_store on a FlStoreBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting FlStoreBean bean
     * @throws DAOException
     */
    //29
    public FlStoreBean decodeRow(ResultSet rs,FlStoreBean bean) throws DAOException
    {
        if(null==bean)
            bean = this.createBean();
        try
        {
            bean.setMd5(rs.getString(1));
            bean.setEncoding(rs.getString(2));
            bean.setData(rs.getBytes(3));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the fl_store table on a FlStoreBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting FlStoreBean bean
     * @throws DAOException
     */
    //30
    public FlStoreBean decodeRow(ResultSet rs, int[] fieldList,FlStoreBean bean) throws DAOException
    {
        if(null==bean)
            bean = this.createBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case FL_STORE_ID_MD5:
                        ++pos;
                        bean.setMd5(rs.getString(pos));
                        break;
                    case FL_STORE_ID_ENCODING:
                        ++pos;
                        bean.setEncoding(rs.getString(pos));
                        break;
                    case FL_STORE_ID_DATA:
                        ++pos;
                        bean.setData(rs.getBytes(pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the fl_store on a FlStoreBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting FlStoreBean bean
     * @throws DAOException
     */
    //31
    public FlStoreBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        FlStoreBean bean = this.createBean();
        try
        {
            bean.setMd5(rs.getString("md5"));
            bean.setEncoding(rs.getString("encoding"));
            bean.setData(rs.getBytes("data"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of FlStoreBean
     * @throws DAOException
     */
    //32
    public FlStoreBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of FlStoreBean
     * @throws DAOException
     */
    //32
    public List<FlStoreBean> loadByPreparedStatementAsList(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatementAsList(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of FlStoreBean
     * @throws DAOException
     */
    //33
    public FlStoreBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        return this.loadByPreparedStatementAsList(ps, fieldList).toArray(new FlStoreBean[0]);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of FlStoreBean
     * @throws DAOException
     */
    //33
    public List<FlStoreBean> loadByPreparedStatementAsList(PreparedStatement ps, int[] fieldList) throws DAOException
    { 
        return loadByPreparedStatementAsList(ps,fieldList,1,-1);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of FlStoreBean
     * @throws DAOException
     */
    //34
    public FlStoreBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        return loadByPreparedStatementAsList(ps,fieldList,startRow,numRows).toArray(new FlStoreBean[0]);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of FlStoreBean
     * @throws DAOException
     */
    //34-1
    public List<FlStoreBean> loadByPreparedStatementAsList(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ListAction action = new ListAction();
        loadByPreparedStatement(ps,fieldList,startRow,numRows,action);
        return action.getList();
    }
    /**
     * Loads each element using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows 
     * and dealt by action.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @param action Action object for do something(not null)
     * @return the count dealt by action
     * @throws DAOException
     */     
    //34-2
    public int loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows,Action<FlStoreBean> action) throws DAOException
    {
        ResultSet rs =  null;
        try {
            ps.setFetchSize(100);
            rs = ps.executeQuery();
            return this.actionOnResultSet(rs, fieldList, startRow, numRows, action);
        } catch (DAOException e) {
            throw e;
        } catch (SQLException e) {
            throw new DataAccessException(e);
        } finally {
            this.getManager().close(rs);
        }
    }
    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    class ListenerContainer implements TableListener<FlStoreBean> {
        private final Set<TableListener<FlStoreBean>> listeners = new TreeSet<TableListener<FlStoreBean>>();
        public ListenerContainer() {
        }
    
        @Override
        public void beforeInsert(FlStoreBean bean) throws DAOException {
            for(TableListener<FlStoreBean> listener:listeners){
                listener.beforeInsert(bean);
            }
        }
    
        @Override
        public void afterInsert(FlStoreBean bean) throws DAOException {
            for(TableListener<FlStoreBean> listener:listeners){
                listener.afterInsert(bean);
            }
        }
    
        @Override
        public void beforeUpdate(FlStoreBean bean) throws DAOException {
            for(TableListener<FlStoreBean> listener:listeners){
                listener.beforeUpdate(bean);
            }
        }
    
        @Override
        public void afterUpdate(FlStoreBean bean) throws DAOException {
            for(TableListener<FlStoreBean> listener:listeners){
                listener.afterUpdate(bean);
            }
        }
    
        @Override
        public void beforeDelete(FlStoreBean bean) throws DAOException {
            for(TableListener<FlStoreBean> listener:listeners){
                listener.beforeDelete(bean);
            }
        }
    
        @Override
        public void afterDelete(FlStoreBean bean) throws DAOException {
            for(TableListener<FlStoreBean> listener:listeners){
                listener.afterDelete(bean);
            }
        }
    
        public boolean isEmpty() {
            return listeners.isEmpty();
        }
    
        public boolean contains(TableListener<FlStoreBean> o) {
            return listeners.contains(o);
        }
    
        public synchronized boolean add(TableListener<FlStoreBean> e) {
            if(null == e)
                throw new NullPointerException();
            return listeners.add(e);
        }
    
        public synchronized boolean remove(TableListener<FlStoreBean> o) {
            return null == o? false : listeners.remove(o);
        }
    
        public synchronized void clear() {
            listeners.clear();
        }    
    }
    private final ListenerContainer listenerContainer = new ListenerContainer();

    //35
    @Override
    public void registerListener(TableListener<FlStoreBean> listener)
    {
        this.listenerContainer.add(listener);
    }

    /**
     * remove listener.
     */
    //36
    @Override
    public void unregisterListener(TableListener<FlStoreBean> listener)
    {
        this.listenerContainer.remove(listener);
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    private Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    private void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    private Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }

    //43
    @Override
    public boolean isPrimaryKey(String column){
        for(String c:PRIMARYKEY_NAMES)if(c.equalsIgnoreCase(column))return true;
        return false;
    }
    
    /**
     * Fill the given prepared statement with the values in argList
     * @param ps the PreparedStatement that will be filled
     * @param argList the arguments to use fill given prepared statement
     * @throws DAOException
     */
    private void fillPrepareStatement(PreparedStatement ps, Object[] argList) throws DAOException{
        try {
            if (!(argList == null || ps == null)) {
                for (int i = 0; i < argList.length; i++) {
                    if (argList[i].getClass().equals(byte[].class)) {
                        ps.setBytes(i + 1, (byte[]) argList[i]);
                    } else
                        ps.setObject(i + 1, argList[i]);
                }
            }
        } catch (SQLException e) {
            throw new DAOException(e);
        }
    }
    
    @Override    
    public int loadBySqlForAction(String sql, Object[] argList, int[] fieldList,int startRow, int numRows,Action<FlStoreBean> action) throws DAOException{
        PreparedStatement ps = null;
        Connection connection = null;
        // logger.debug("sql string:\n" + sql + "\n");
        try {
            connection = this.getConnection();
            ps = connection.prepareStatement(sql,
                    ResultSet.TYPE_FORWARD_ONLY,
                    ResultSet.CONCUR_READ_ONLY);
            fillPrepareStatement(ps, argList);
            return this.loadByPreparedStatement(ps, fieldList, startRow, numRows, action);
        } catch (DAOException e) {
            throw e;
        }catch (SQLException e) {
            throw new DataAccessException(e);
        } finally {
            this.getManager().close(ps);
            this.freeConnection(connection);
        }
    }
   
    @Override
    public <T>T runAsTransaction(Callable<T> fun) throws DAOException{
        return Manager.getInstance().runAsTransaction(fun);
    }
    
    class DeleteBeanAction extends Action.Adapter<FlStoreBean>{
        private final AtomicInteger count=new AtomicInteger(0);
        @Override
        public void call(FlStoreBean bean) throws DAOException {
                FlStoreManager.this.delete(bean);
                count.incrementAndGet();
        }
        int getCount(){
            return count.get();
        }
    }
}
