// ______________________________________________________
// Generated by sql2java - https://github.com/10km/sql2java-2-6-7 (custom branch) 
// modified by guyadong from
// sql2java original version https://sourceforge.net/projects/sql2java/ 
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
// ______________________________________________________

package net.gdface.facelog.db.mysql;

import java.util.concurrent.Callable;

import net.gdface.facelog.db.PersonBean;
import net.gdface.facelog.db.IBeanConverter;
import net.gdface.facelog.db.IDbConverter;
import net.gdface.facelog.db.BaseBean;
import net.gdface.facelog.db.TableManager;
import net.gdface.facelog.db.FaceBean;
import net.gdface.facelog.db.LogBean;
import net.gdface.facelog.db.ImageBean;
import net.gdface.facelog.db.TableListener;
import net.gdface.facelog.db.WrapDAOException;

import net.gdface.facelog.dborm.exception.DAOException;
import net.gdface.facelog.dborm.person.FlPersonManager;
import net.gdface.facelog.dborm.person.FlPersonBean;
import net.gdface.facelog.dborm.face.FlFaceBean;
import net.gdface.facelog.dborm.log.FlLogBean;
/**
 * Handles database calls (save, load, count, etc...) for the fl_person table.<br>
 * all {@link DAOException} be wrapped as {@link WrapDAOException} to throw.
 * @author guyadong
 */
public class PersonManager extends TableManager.Adapter<PersonBean>
{
    private FlPersonManager nativeManager = FlPersonManager.getInstance();
    private IDbConverter<net.gdface.facelog.dborm.device.FlDeviceBean,net.gdface.facelog.dborm.face.FlFaceBean,net.gdface.facelog.dborm.image.FlImageBean,net.gdface.facelog.dborm.log.FlLogBean,net.gdface.facelog.dborm.person.FlPersonBean,net.gdface.facelog.dborm.image.FlStoreBean,net.gdface.facelog.dborm.face.FlFaceLightBean,net.gdface.facelog.dborm.face.FlFeatureBean,net.gdface.facelog.dborm.log.FlLogLightBean> dbConverter = DbConverter.INSTANCE;
    private IBeanConverter<PersonBean,FlPersonBean> beanConverter = dbConverter.getPersonBeanConverter();
    private static PersonManager singleton = new PersonManager();

    /**
    * @return table name
    */
    public String getTableName() {
        return this.nativeManager.getTableName();
    }

    /**
    * @return field names of table
    */
    public String[] getFieldNames() {
        return this.nativeManager.getFieldNames();
    }

    public String getFieldNamesAsString() {
        return this.nativeManager.getFieldNamesAsString();
    }
    
    public String[] getFullFieldNames() {
        return this.nativeManager.getFullFieldNames();
    }
    
    /**
    * @return primarykeyNames
    */
    public String[] getPrimarykeyNames() {
        return this.nativeManager.getPrimarykeyNames();
    }
    
    /**
     * Get the {@link PersonManager} singleton.
     *
     * @return {@link PersonManager}
     */
    public static PersonManager getInstance()
    {
        return singleton;
    }
   
    public IDbConverter<net.gdface.facelog.dborm.device.FlDeviceBean,net.gdface.facelog.dborm.face.FlFaceBean,net.gdface.facelog.dborm.image.FlImageBean,net.gdface.facelog.dborm.log.FlLogBean,net.gdface.facelog.dborm.person.FlPersonBean,net.gdface.facelog.dborm.image.FlStoreBean,net.gdface.facelog.dborm.face.FlFaceLightBean,net.gdface.facelog.dborm.face.FlFeatureBean,net.gdface.facelog.dborm.log.FlLogLightBean> getDbConverter() {
        return dbConverter;
    }

    /**
     * set  {@link IDbConverter} as converter used by manager.<br>
     * throw {@link NullPointerException} if {@code dbConverter} is null
     * @param dbConverter
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    public synchronized void setDbConverter(IDbConverter dbConverter) {
        if( null == dbConverter)
            throw new NullPointerException();
        this.dbConverter = dbConverter;
        this.beanConverter = this.dbConverter.getPersonBeanConverter();
    }
    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a {@link PersonBean} from the fl_person using primary key fields.
     *
     * @param id Integer - PK# 1
     * @return a unique PersonBean or {@code null} if not found
     */
    //1
    public PersonBean loadByPrimaryKey(Integer id)
    {
        try{
            return this.beanConverter.fromRight(nativeManager.loadByPrimaryKey(id));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //1.2
    @Override
    public PersonBean loadByPrimaryKey(PersonBean bean)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadByPrimaryKey(this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    /**
     * Loads a {@link PersonBean} from the fl_person using primary key fields.
     * when you don't know which is primary key of table,you can use the method.
     * @param keys primary keys value:<br> 
     *             PK# 1:Integer     
     * @return a unique {@link PersonBean} or {@code null} if not found
     * @see {@link #loadByPrimaryKey(Integer id)}
     */
    //1.3
    public PersonBean loadByPrimaryKey(Object ...keys){
        if(keys.length != 1 )
            throw new IllegalArgumentException("argument number mismatch with primary key number");
        if(! (keys[0] instanceof Integer))
            throw new IllegalArgumentException("invalid type for the No.1 argument,expected type:Integer");
        return loadByPrimaryKey((Integer)keys[0]);
    }
    
    /**
     * Returns true if this fl_person contains row with primary key fields.
     * @param id Integer - PK# 1
     * @see #loadByPrimaryKey(Integer id)
     */
    //1.4
    public boolean existsPrimaryKey(Integer id)
    {
        return null!=loadByPrimaryKey(id );
    }
    
    /**
     * Delete row according to its primary keys.<br>
     * all keys must not be null
     *
     * @param id Integer - PK# 1
     * @return the number of deleted rows
     */
    //2
    public int deleteByPrimaryKey(Integer id)
    {
        try
        {
            return nativeManager.deleteByPrimaryKey(id);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * Delete row according to its primary keys.
     *
     * @param keys primary keys value:<br> 
     *             PK# 1:Integer     
     * @return the number of deleted rows
     * @see {@link #deleteByPrimaryKey(Integer id)}
     */   
    //2.1
    public int deleteByPrimaryKey(Object ...keys){
        if(keys.length != 1 )
            throw new IllegalArgumentException("argument number mismatch with primary key number");
        if(! (keys[0] instanceof Integer))
            throw new IllegalArgumentException("invalid type for the No.1 argument,expected type:Integer");
        return deleteByPrimaryKey((Integer)keys[0]);
    }

 
    //////////////////////////////////////
    // IMPORT KEY GENERIC METHOD
    //////////////////////////////////////
    
    /**
     * Retrieves imported T objects by ikIndex.<br>
     * @param <T>
     * <ul>
     *     <li> {@link TableManager#FL_PERSON_IK_FL_FACE_PERSON_ID} -> {@link FlFaceBean}</li>
     *     <li> {@link TableManager#FL_PERSON_IK_FL_LOG_PERSON_ID} -> {@link FlLogBean}</li>
     * </ul>
     * @param bean the {@link PersonBean} object to use
     * @param ikIndex valid values: {@link TableManager#FL_PERSON_IK_FL_FACE_PERSON_ID},{@link TableManager#FL_PERSON_IK_FL_LOG_PERSON_ID}
     * @return the associated T beans or {@code null} if {@code bean} is {@code null}
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends BaseBean> java.util.List<T> getImportedBeansAsList(PersonBean bean,int ikIndex){
        switch(ikIndex){
        case FL_PERSON_IK_FL_FACE_PERSON_ID:
            return (java.util.List<T>)this.getFlFaceBeansByPersonIdAsList(bean);
        case FL_PERSON_IK_FL_LOG_PERSON_ID:
            return (java.util.List<T>)this.getFlLogBeansByPersonIdAsList(bean);
        }
        throw new IllegalArgumentException(String.format("invalid ikIndex %d", ikIndex));
    }
    /**
     * Set the T objects as imported beans of bean object by ikIndex.<br>
     * @param <T>
     * 
     * <ul>
     *     <li> {@link TableManager#FL_PERSON_IK_FL_FACE_PERSON_ID} -> {@link FlFaceBean}</li>
     *     <li> {@link TableManager#FL_PERSON_IK_FL_LOG_PERSON_ID} -> {@link FlLogBean}</li>
     * </ul>
     * @param bean the {@link PersonBean} object to use
     * @param importedBeans the FlLogBean array to associate to the {@link PersonBean}
     * @param ikIndex valid values: {@link TableManager#FL_PERSON_IK_FL_FACE_PERSON_ID},{@link TableManager#FL_PERSON_IK_FL_LOG_PERSON_ID}
     * @return importedBeans always
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends BaseBean> T[] setImportedBeans(PersonBean bean,T[] importedBeans,int ikIndex){
        switch(ikIndex){
        case FL_PERSON_IK_FL_FACE_PERSON_ID:
            return (T[])setFlFaceBeansByPersonId(bean,(FaceBean[])importedBeans);
        case FL_PERSON_IK_FL_LOG_PERSON_ID:
            return (T[])setFlLogBeansByPersonId(bean,(LogBean[])importedBeans);
        }
        throw new IllegalArgumentException(String.format("invalid ikIndex %d", ikIndex));
    }
    /**
     * Set the importedBeans associates to the bean by ikIndex<br>
     * @param <T>
     * <ul>
     *     <li> {@link TableManager#FL_PERSON_IK_FL_FACE_PERSON_ID} -> {@link FlFaceBean}</li>
     *     <li> {@link TableManager#FL_PERSON_IK_FL_LOG_PERSON_ID} -> {@link FlLogBean}</li>
     * </ul>
     * @param bean the {@link PersonBean} object to use
     * @param importedBeans the <T> object to associate to the {@link PersonBean}
     * @param ikIndex valid values: {@link TableManager#FL_PERSON_IK_FL_FACE_PERSON_ID},{@link TableManager#FL_PERSON_IK_FL_LOG_PERSON_ID}
     * @return importedBeans always
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends BaseBean,C extends java.util.Collection<T>> C setImportedBeans(PersonBean bean,C importedBeans,int ikIndex){
        switch(ikIndex){
        case FL_PERSON_IK_FL_FACE_PERSON_ID:
            return (C)setFlFaceBeansByPersonId(bean,(java.util.Collection<FaceBean>)importedBeans);
        case FL_PERSON_IK_FL_LOG_PERSON_ID:
            return (C)setFlLogBeansByPersonId(bean,(java.util.Collection<LogBean>)importedBeans);
        }
        throw new IllegalArgumentException(String.format("invalid ikIndex %d", ikIndex));
    }
 

    //////////////////////////////////////
    // GET/SET IMPORTED KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the {@link FaceBean} object from the fl_face.person_id field.<BR>
     * FK_NAME : fl_face_ibfk_2 
     * @param bean the {@link PersonBean}
     * @return the associated {@link FaceBean} beans or {@code null} if {@code bean} is {@code null}
     */
    //3.1 GET IMPORTED
    public FaceBean[] getFlFaceBeansByPersonId(PersonBean bean)
    {
        return this.getFlFaceBeansByPersonIdAsList(bean).toArray(new FaceBean[0]);
    }

    /**
     * Retrieves the {@link FaceBean} object from fl_face.person_id field.<BR>
     * FK_NAME:fl_face_ibfk_2
     * @param bean the {@link PersonBean}
     * @return the associated {@link FaceBean} beans or {@code null} if {@code bean} is {@code null}
     */
    //3.2 GET IMPORTED
    public java.util.List<FaceBean> getFlFaceBeansByPersonIdAsList(PersonBean bean)
    {
        try {
            return this.dbConverter.getFaceBeanConverter().fromRight(nativeManager.getFlFaceBeansByPersonIdAsList( this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * set  the {@link FaceBean} object array associate to PersonBean by the fl_face.person_id field.<BR>
     * FK_NAME : fl_face_ibfk_2 
     * @param bean the referenced {@link PersonBean}
     * @param importedBeans imported beans from fl_face
     * @return importedBeans always
     * @see {@link FlFaceManager#setReferencedByPersonId(FaceBean, PersonBean)
     */
    //3.3 SET IMPORTED
    public FaceBean[] setFlFaceBeansByPersonId(PersonBean bean , FaceBean[] importedBeans)
    {
        try {
            IBeanConverter<FaceBean,FlFaceBean> importedConverter = this.dbConverter.getFaceBeanConverter();
            return importedConverter.fromRight(importedBeans,
                this.nativeManager.setFlFaceBeansByPersonId(
                    this.beanConverter.toRight(bean),
                    importedConverter.toRight(importedBeans)
                ));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * set  the {@link FaceBean} object java.util.Collection associate to PersonBean by the fl_face.person_id field.<BR>
     * FK_NAME:fl_face_ibfk_2
     * @param bean the referenced {@link PersonBean} 
     * @param importedBeans imported beans from fl_face 
     * @return importedBeans always
     * @see {@link FlFaceManager#setReferencedByPersonId(FaceBean, PersonBean)
     */
    //3.4 SET IMPORTED
    public <C extends java.util.Collection<FaceBean>> C setFlFaceBeansByPersonId(PersonBean bean , C importedBeans)
    {
        try {
            IBeanConverter<FaceBean,FlFaceBean> importedConverter = this.dbConverter.getFaceBeanConverter();
            if(importedBeans instanceof java.util.List){
                importedConverter.fromRight((java.util.List<FaceBean>)importedBeans,nativeManager.setFlFaceBeansByPersonId(
                    this.beanConverter.toRight(bean),
                    importedConverter.toRight(importedBeans)
                    ));
            }else{
                FaceBean[] array = importedBeans.toArray(new FaceBean[0]);
                importedConverter.fromRight(array,nativeManager.setFlFaceBeansByPersonId(
                    this.beanConverter.toRight(bean),
                    importedConverter.toRight(array)
                    ));
            }
            return importedBeans;
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * Retrieves the {@link LogBean} object from the fl_log.person_id field.<BR>
     * FK_NAME : fl_log_ibfk_1 
     * @param bean the {@link PersonBean}
     * @return the associated {@link LogBean} beans or {@code null} if {@code bean} is {@code null}
     */
    //3.1 GET IMPORTED
    public LogBean[] getFlLogBeansByPersonId(PersonBean bean)
    {
        return this.getFlLogBeansByPersonIdAsList(bean).toArray(new LogBean[0]);
    }

    /**
     * Retrieves the {@link LogBean} object from fl_log.person_id field.<BR>
     * FK_NAME:fl_log_ibfk_1
     * @param bean the {@link PersonBean}
     * @return the associated {@link LogBean} beans or {@code null} if {@code bean} is {@code null}
     */
    //3.2 GET IMPORTED
    public java.util.List<LogBean> getFlLogBeansByPersonIdAsList(PersonBean bean)
    {
        try {
            return this.dbConverter.getLogBeanConverter().fromRight(nativeManager.getFlLogBeansByPersonIdAsList( this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * set  the {@link LogBean} object array associate to PersonBean by the fl_log.person_id field.<BR>
     * FK_NAME : fl_log_ibfk_1 
     * @param bean the referenced {@link PersonBean}
     * @param importedBeans imported beans from fl_log
     * @return importedBeans always
     * @see {@link FlLogManager#setReferencedByPersonId(LogBean, PersonBean)
     */
    //3.3 SET IMPORTED
    public LogBean[] setFlLogBeansByPersonId(PersonBean bean , LogBean[] importedBeans)
    {
        try {
            IBeanConverter<LogBean,FlLogBean> importedConverter = this.dbConverter.getLogBeanConverter();
            return importedConverter.fromRight(importedBeans,
                this.nativeManager.setFlLogBeansByPersonId(
                    this.beanConverter.toRight(bean),
                    importedConverter.toRight(importedBeans)
                ));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * set  the {@link LogBean} object java.util.Collection associate to PersonBean by the fl_log.person_id field.<BR>
     * FK_NAME:fl_log_ibfk_1
     * @param bean the referenced {@link PersonBean} 
     * @param importedBeans imported beans from fl_log 
     * @return importedBeans always
     * @see {@link FlLogManager#setReferencedByPersonId(LogBean, PersonBean)
     */
    //3.4 SET IMPORTED
    public <C extends java.util.Collection<LogBean>> C setFlLogBeansByPersonId(PersonBean bean , C importedBeans)
    {
        try {
            IBeanConverter<LogBean,FlLogBean> importedConverter = this.dbConverter.getLogBeanConverter();
            if(importedBeans instanceof java.util.List){
                importedConverter.fromRight((java.util.List<LogBean>)importedBeans,nativeManager.setFlLogBeansByPersonId(
                    this.beanConverter.toRight(bean),
                    importedConverter.toRight(importedBeans)
                    ));
            }else{
                LogBean[] array = importedBeans.toArray(new LogBean[0]);
                importedConverter.fromRight(array,nativeManager.setFlLogBeansByPersonId(
                    this.beanConverter.toRight(bean),
                    importedConverter.toRight(array)
                    ));
            }
            return importedBeans;
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }



    /**
     * Save the PersonBean bean and referenced beans and imported beans into the database.
     *
     * @param bean the {@link PersonBean} bean to be saved
     * @param refFlImagebyPhotoId the {@link ImageBean} bean referenced by {@link PersonBean} 
     * @param impFlFacebyPersonId the {@link FaceBean} bean refer to {@link PersonBean} 
     * @param impFlLogbyPersonId the {@link LogBean} bean refer to {@link PersonBean} 
     * @return the inserted or updated {@link PersonBean} bean
     */
    //3.5 SYNC SAVE 
    public PersonBean save(PersonBean bean
        , ImageBean refFlImagebyPhotoId 
        , FaceBean[] impFlFacebyPersonId , LogBean[] impFlLogbyPersonId )
    {
        try{
            return this.beanConverter.fromRight(bean,nativeManager.save(this.beanConverter.toRight(bean)
                , this.dbConverter.getImageBeanConverter().toRight(refFlImagebyPhotoId)                 , this.dbConverter.getFaceBeanConverter().toRight(impFlFacebyPersonId)  , this.dbConverter.getLogBeanConverter().toRight(impFlLogbyPersonId)  ));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    } 
    /**
     * Transaction version for sync save
     * @see {@link #save(PersonBean , ImageBean , FaceBean[] , LogBean[] )}
     */
    //3.6 SYNC SAVE AS TRANSACTION
    public PersonBean saveAsTransaction(final PersonBean bean
        ,final ImageBean refFlImagebyPhotoId 
        ,final FaceBean[] impFlFacebyPersonId ,final LogBean[] impFlLogbyPersonId )
    {
        return this.runAsTransaction(new Callable<PersonBean>(){
            @Override
            public PersonBean call() throws Exception {
                return save(bean , refFlImagebyPhotoId , impFlFacebyPersonId , impFlLogbyPersonId );
            }});
    }
    /**
     * Save the PersonBean bean and referenced beans and imported beans into the database.
     *
     * @param bean the {@link PersonBean} bean to be saved
     * @param refFlImagebyPhotoId the {@link ImageBean} bean referenced by {@link PersonBean} 
     * @param impFlFacebyPersonId the {@link FaceBean} bean refer to {@link PersonBean} 
     * @param impFlLogbyPersonId the {@link LogBean} bean refer to {@link PersonBean} 
     * @return the inserted or updated {@link PersonBean} bean
     */
    //3.7 SYNC SAVE 
    public PersonBean save(PersonBean bean
        , ImageBean refFlImagebyPhotoId 
        , java.util.Collection<FaceBean> impFlFacebyPersonId , java.util.Collection<LogBean> impFlLogbyPersonId )
    {
        try{
            return this.beanConverter.fromRight(bean,nativeManager.save(this.beanConverter.toRight(bean)
                , this.dbConverter.getImageBeanConverter().toRight(refFlImagebyPhotoId)                 , this.dbConverter.getFaceBeanConverter().toRight(impFlFacebyPersonId)  , this.dbConverter.getLogBeanConverter().toRight(impFlLogbyPersonId)  ));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }   
    /**
     * Transaction version for sync save
     * @see {@link #save(PersonBean , ImageBean , java.util.Collection , java.util.Collection )}
     */
    //3.8 SYNC SAVE AS TRANSACTION
    public PersonBean saveAsTransaction(final PersonBean bean
        ,final ImageBean refFlImagebyPhotoId 
        ,final  java.util.Collection<FaceBean> impFlFacebyPersonId ,final  java.util.Collection<LogBean> impFlLogbyPersonId )
    {
        return this.runAsTransaction(new Callable<PersonBean>(){
            @Override
            public PersonBean call() throws Exception {
                return save(bean , refFlImagebyPhotoId , impFlFacebyPersonId , impFlLogbyPersonId );
            }});
    }
      //////////////////////////////////////
    // FOREIGN KEY GENERIC METHOD
    //////////////////////////////////////

    /**
     * Retrieves the bean object referenced by fkIndex.<br>
     * @param <T>
     * <ul>
     *     <li> {@link TableManager#FL_PERSON_FK_PHOTO_ID} -> {@link ImageBean}</li>
     * </ul>
     * @param bean the {@link PersonBean} object to use
     * @param fkIndex valid values: <br>
     *        {@link TableManager#FL_PERSON_FK_PHOTO_ID}
     * @return the associated <T> bean or {@code null} if {@code bean} or {@code beanToSet} is {@code null}
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends BaseBean> T getReferencedBean(PersonBean bean,int fkIndex){
        switch(fkIndex){
        case FL_PERSON_FK_PHOTO_ID:
            return  (T)this.getReferencedByPhotoId(bean);
        }
        throw new IllegalArgumentException(String.format("invalid fkIndex %d", fkIndex));
    }
    /**
     * Associates the {@link PersonBean} object to the bean object by fkIndex field.<br>
     * 
     * @param <T> see also {@link #getReferencedBean(PersonBean,int)}
     * @param bean the {@link PersonBean} object to use
     * @param beanToSet the <T> object to associate to the {@link PersonBean}
     * @param fkIndex valid values: see also {@link #getReferencedBean(PersonBean,int)}
     * @return always beanToSet saved
     */
    @SuppressWarnings("unchecked")
    @Override
    public <T extends BaseBean> T setReferencedBean(PersonBean bean,T beanToSet,int fkIndex){
        switch(fkIndex){
        case FL_PERSON_FK_PHOTO_ID:
            return  (T)this.setReferencedByPhotoId(bean, (ImageBean)beanToSet);
        }
        throw new IllegalArgumentException(String.format("invalid fkIndex %d", fkIndex));
    }
    
    //////////////////////////////////////
    // GET/SET FOREIGN KEY BEAN METHOD
    //////////////////////////////////////


    /**
     * Retrieves the {@link ImageBean} object referenced by {@link PersonBean#getPhotoId}() field.<br>
     * FK_NAME : fl_person_ibfk_1
     * @param bean the {@link PersonBean}
     * @return the associated {@link ImageBean} bean or {@code null} if {@code bean} is {@code null}
     */
    //3.2 GET REFERENCED VALUE
    public ImageBean getReferencedByPhotoId(PersonBean bean)
    {
        try{
            return this.dbConverter.getImageBeanConverter().fromRight(this.nativeManager.getReferencedByPhotoId(this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
        
    }

    /**
     * Associates the {@link PersonBean} object to the {@link ImageBean} object by {@link PersonBean#getPhotoId}() field.
     *
     * @param bean the {@link PersonBean} object to use
     * @param beanToSet the {@link ImageBean} object to associate to the {@link PersonBean}
     * @return always beanToSet saved
     * @throws Exception
     */
    //5.2 SET REFERENCED 
    public ImageBean setReferencedByPhotoId(PersonBean bean, ImageBean beanToSet)
    {
        try{
            return this.dbConverter.getImageBeanConverter().fromRight(beanToSet,this.nativeManager.setReferencedByPhotoId(this.beanConverter.toRight(bean),this.dbConverter.getImageBeanConverter().toRight(beanToSet)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////

    //11
    @Override
    public int deleteByWhere(String where)
    {
        try{
            return this.nativeManager.deleteByWhere(where);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________

    //13
    @Override
    protected PersonBean insert(PersonBean bean)
    {
        try{
            return this.beanConverter.fromRight(bean,this.nativeManager.insert(this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //14
    @Override
    protected PersonBean update(PersonBean bean)
    {
        try{
            return this.beanConverter.fromRight(bean,this.nativeManager.update(this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________
    //18
    @Override
    public PersonBean loadUniqueUsingTemplate(PersonBean bean)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadUniqueUsingTemplate(this.beanConverter.toRight(bean)));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
     }

    //20-5
    @Override
    public int loadUsingTemplate(PersonBean bean, int[] fieldList, int startRow, int numRows,int searchType, Action<PersonBean> action)
    {
        try {
            return this.nativeManager.loadUsingTemplate(this.beanConverter.toRight(bean),fieldList,startRow,numRows,searchType,this.toNative(action));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //21
    @Override
    public int deleteUsingTemplate(PersonBean bean)
    {
        try{
            return this.nativeManager.deleteUsingTemplate(this.beanConverter.toRight(bean));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }


    //_____________________________________________________________________
    //
    // USING INDICES
    //_____________________________________________________________________

    /**
     * Retrieves an unique PersonBean using the face_md5 index.
     *
     * @param faceMd5 the face_md5 column's value filter. must not be null
     * @return an array of PersonBean
     */
    public PersonBean loadByindexFaceMd5(String faceMd5)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadByindexFaceMd5(faceMd5));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }


    /**
     * Deletes rows using the face_md5 index.
     *
     * @param faceMd5 the face_md5 column's value filter.
     * @return the number of deleted objects
     */
    public int deleteByindexFaceMd5(String faceMd5)
    {
        try{
            return this.nativeManager.deleteByindexFaceMd5(faceMd5);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    
    /**
     * Retrieves an unique PersonBean using the papers_num index.
     *
     * @param papersNum the papers_num column's value filter. must not be null
     * @return an array of PersonBean
     */
    public PersonBean loadByindexPapersNum(String papersNum)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadByindexPapersNum(papersNum));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }


    /**
     * Deletes rows using the papers_num index.
     *
     * @param papersNum the papers_num column's value filter.
     * @return the number of deleted objects
     */
    public int deleteByindexPapersNum(String papersNum)
    {
        try{
            return this.nativeManager.deleteByindexPapersNum(papersNum);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    
    /**
     * Retrieves an unique PersonBean using the photo_id index.
     *
     * @param photoId the photo_id column's value filter. must not be null
     * @return an array of PersonBean
     */
    public PersonBean loadByindexPhotoId(String photoId)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadByindexPhotoId(photoId));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }


    /**
     * Deletes rows using the photo_id index.
     *
     * @param photoId the photo_id column's value filter.
     * @return the number of deleted objects
     */
    public int deleteByindexPhotoId(String photoId)
    {
        try{
            return this.nativeManager.deleteByindexPhotoId(photoId);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    
     /**
     * Retrieves an array of PersonBean using the expiry_date index.
     *
     * @param expiryDate the expiry_date column's value filter.
     * @return an array of PersonBean
     */
    public PersonBean[] loadByindexExpiryDate(java.util.Date expiryDate)
    {
        return this.loadByindexExpiryDateAsList(expiryDate).toArray(new PersonBean[0]);
    }
    
    /**
     * Retrieves a list of PersonBean using the expiry_date index.
     *
     * @param expiryDate the expiry_date column's value filter.
     * @return a list of PersonBean
     */
    public java.util.List<PersonBean> loadByindexExpiryDateAsList(java.util.Date expiryDate)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadByindexExpiryDateAsList(expiryDate));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    /**
     * Deletes rows using the expiry_date index.
     *
     * @param expiryDate the expiry_date column's value filter.
     * @return the number of deleted objects
     */
    public int deleteByindexExpiryDate(java.util.Date expiryDate)
    {
        try{
            return this.nativeManager.deleteByindexExpiryDate(expiryDate);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    
    
    /**
     * Retrieves a list of PersonBean using the index specified by keyIndex.
     * @param keyIndex valid values: <br>
     *        {@link TableManager#FL_PERSON_INDEX_FACE_MD5},{@link TableManager#FL_PERSON_INDEX_PAPERS_NUM},{@link TableManager#FL_PERSON_INDEX_PHOTO_ID},{@link TableManager#FL_PERSON_INDEX_EXPIRY_DATE}
     * @param keys key values of index
     * @return a list of PersonBean
     */
    @Override
    public java.util.List<PersonBean> loadByIndexAsList(int keyIndex,Object ...keys)
    {
        try{
            return this.beanConverter.fromRight(this.nativeManager.loadByIndexAsList(keyIndex,keys));
        }catch(DAOException e){
            throw new WrapDAOException(e);
        }
    }
    
    /**
     * Deletes rows using key.
     * @param keyIndex valid values: <br>
     *        {@link TableManager#FL_PERSON_INDEX_FACE_MD5},{@link TableManager#FL_PERSON_INDEX_PAPERS_NUM},{@link TableManager#FL_PERSON_INDEX_PHOTO_ID},{@link TableManager#FL_PERSON_INDEX_EXPIRY_DATE}
     * @param keys key values of index
     * @return the number of deleted objects
     */
    @Override
    public int deleteByIndex(int keyIndex,Object ...keys)
    {
        try{
            return this.nativeManager.deleteByIndex(keyIndex,keys);
        }catch(DAOException e){
            throw new WrapDAOException(e);
        }
    }

    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________
    //25
    @Override
    public int countWhere(String where)
    {
        try{
            return this.nativeManager.countWhere(where);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }

    //20
    @Override
    public int countUsingTemplate(PersonBean bean, int searchType)
    {
        try{
            return this.nativeManager.countUsingTemplate(this.beanConverter.toRight(bean),searchType);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }


    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________

    //35
    @Override
    public void registerListener(TableListener<PersonBean> listener)
    {
        this.nativeManager.registerListener(this.toNative(listener));
    }

    //36
    @Override
    public void unregisterListener(TableListener<PersonBean> listener)
    {
        this.nativeManager.unregisterListener(this.toNative(listener));
    }
    
    private net.gdface.facelog.dborm.TableListener<FlPersonBean> toNative(final TableListener<PersonBean> listener) {
        return null == listener ?null:new net.gdface.facelog.dborm.TableListener<FlPersonBean> (){

            @Override
            public void beforeInsert(FlPersonBean bean) throws DAOException {
                listener.beforeInsert(PersonManager.this.beanConverter.fromRight(bean));                
            }

            @Override
            public void afterInsert(FlPersonBean bean) throws DAOException {
                listener.afterInsert(PersonManager.this.beanConverter.fromRight(bean));
                
            }

            @Override
            public void beforeUpdate(FlPersonBean bean) throws DAOException {
                listener.beforeUpdate(PersonManager.this.beanConverter.fromRight(bean));
                
            }

            @Override
            public void afterUpdate(FlPersonBean bean) throws DAOException {
                listener.afterUpdate(PersonManager.this.beanConverter.fromRight(bean));
            }

            @Override
            public void beforeDelete(FlPersonBean bean) throws DAOException {
                listener.beforeDelete(PersonManager.this.beanConverter.fromRight(bean));
            }

            @Override
            public void afterDelete(FlPersonBean bean) throws DAOException {
                listener.afterDelete(PersonManager.this.beanConverter.fromRight(bean));
            }};
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    //43
    @Override
    public boolean isPrimaryKey(String column){
        return this.nativeManager.isPrimaryKey(column);
    }
    
    @Override
    public int loadBySqlForAction(String sql, Object[] argList, int[] fieldList,int startRow, int numRows,Action<PersonBean> action){
        try{
            return this.nativeManager.loadBySqlForAction(sql,argList,fieldList,startRow,numRows,this.toNative(action));
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    
    @Override
    public <T>T runAsTransaction(Callable<T> fun) {
        try{
            return this.nativeManager.runAsTransaction(fun);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    
    @Override
    public void runAsTransaction(final Runnable fun){
        try{
            this.nativeManager.runAsTransaction(fun);
        }
        catch(DAOException e)
        {
            throw new WrapDAOException(e);
        }
    }
    private net.gdface.facelog.dborm.TableManager.Action<FlPersonBean> toNative(final Action<PersonBean> action){
        if(null == action)
            throw new NullPointerException();
        return new net.gdface.facelog.dborm.TableManager.Action<FlPersonBean>(){

            @Override
            public void call(FlPersonBean bean) {
                action.call(PersonManager.this.beanConverter.fromRight(bean));
            }

            @Override
            public FlPersonBean getBean() {
                return  PersonManager.this.beanConverter.toRight(action.getBean());
            }};
    }
}
