// ______________________________________________________
// Generated by sql2java - https://github.com/10km/sql2java-2-6-7 (custom branch) 
// modified by guyadong from
// sql2java original version https://sourceforge.net/projects/sql2java/ 
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
// ______________________________________________________

package net.gdface.facelog.db;


/**
 * Listener that is notified of fl_store table changes.
 * @author guyadong
 */
public interface StoreListener extends TableListener
{
    /**
     * This adapter class provides default implementations for the
     * methods described by the {@link StoreListener} interface.<br>
     * 
     * @see StoreListener
     * @author sql2java
     *
     */
    public static class Adapter implements StoreListener{

        @Override
        public void beforeInsert(StoreBean bean) {}

        @Override
        public void afterInsert(StoreBean bean) {
        }

        @Override
        public void beforeUpdate(StoreBean bean) {}

        @Override
        public void afterUpdate(StoreBean bean) {}

        @Override
        public void beforeDelete(StoreBean bean) {}

        @Override
        public void afterDelete(StoreBean bean) {}
    }
    /**
     * Invoked just before inserting a StoreBean record into the database.
     *
     * @param bean the StoreBean that is about to be inserted
     */
    public void beforeInsert(StoreBean bean);


    /**
     * Invoked just after a StoreBean record is inserted in the database.
     *
     * @param bean the StoreBean that was just inserted
     */
    public void afterInsert(StoreBean bean);


    /**
     * Invoked just before updating a StoreBean record in the database.
     *
     * @param bean the StoreBean that is about to be updated
     */
    public void beforeUpdate(StoreBean bean);


    /**
     * Invoked just after updating a StoreBean record in the database.
     *
     * @param bean the StoreBean that was just updated
     */
    public void afterUpdate(StoreBean bean);


    /**
     * Invoked just before deleting a StoreBean record in the database.
     *
     * @param bean the StoreBean that is about to be deleted
     */
    public void beforeDelete(StoreBean bean);


    /**
     * Invoked just after deleting a StoreBean record in the database.
     *
     * @param bean the StoreBean that was just deleted
     */
    public void afterDelete(StoreBean bean);

}
